# CLEANING THE **FILE**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Titanic.csv to Titanic (4).csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Titanic.csv')

In [ ]:
df.head(10)

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
df.tail()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.shape

(891, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    object
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    object
 9   class        891 non-null    object
 10  who          891 non-null    object
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    object
 13  embark_town  889 non-null    object
 14  alive        891 non-null    object
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(7)
memory usage: 99.3+ KB

In [ ]:
df.drop("deck", axis=1, inplace=True)

In [ ]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [ ]:
df["age"] = df["age"].fillna(df["age"].mean())

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

In [ ]:
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  891 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

In [ ]:
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  891 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(6)
memory usage: 85.4+ KB

In [ ]:
df["embarked"].isnull().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(111)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.shape

(780, 14)

In [ ]:
df["sex"]

0        male
1      female
2      female
3      female
4        male
        ...
885    female
887    female
888    female
889      male
890      male
Name: sex, Length: 780, dtype: object

In [ ]:
df["sex"]=df["sex"].map({"male":1,"female":0})

In [ ]:
df["sex"]

0      1
1      0
2      0
3      0
4      1
      ..
885    0
887    0
888    0
889    1
890    1
Name: sex, Length: 780, dtype: int64

In [ ]:
df["adult_male"]=df["adult_male"].map({True:1,False:0})

In [ ]:
df["alone"]

0      False
1      False
2       True
3      False
4       True
       ...
885    False
887     True
888    False
889     True
890     True
Name: alone, Length: 780, dtype: bool

In [ ]:
df["alone"]=df["alone"].map({True:1,False:0})

In [ ]:
df['alone']

0      0
1      0
2      1
3      0
4      1
      ..
885    0
887    1
888    0
889    1
890    1
Name: alone, Length: 780, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     780 non-null    int64
 1   pclass       780 non-null    int64
 2   sex          780 non-null    int64
 3   age          780 non-null    float64
 4   sibsp        780 non-null    int64
 5   parch        780 non-null    int64
 6   fare         780 non-null    float64
 7   embarked     780 non-null    object
 8   class        780 non-null    object
 9   who          780 non-null    object
 10  adult_male   780 non-null    int64
 11  embark_town  780 non-null    object
 12  alive        780 non-null    object
 13  alone        780 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 91.4+ KB

In [ ]:
df=pd.get_dummies(df,columns=["embarked"],drop_first=True)

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked_Q,embarked_S
0,0,3,1,22.0,1,0,7.2500,Third,man,1,Southampton,no,0,False,True
1,1,1,0,38.0,1,0,71.2833,First,woman,0,Cherbourg,yes,0,False,False
2,1,3,0,26.0,0,0,7.9250,Third,woman,0,Southampton,yes,1,False,True
3,1,1,0,35.0,1,0,53.1000,First,woman,0,Southampton,yes,0,False,True
4,0,3,1,35.0,0,0,8.0500,Third,man,1,Southampton,no,1,False,True

In [ ]:
df["who"].value_counts()

who
man      448
woman    250
child     82
Name: count, dtype: int64

In [ ]:
df['embark_town']

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...
885     Queenstown
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 780, dtype: object

In [ ]:
df=pd.get_dummies(df,columns=["embark_town"],drop_first=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    object
 8   who                      780 non-null    object
 9   adult_male               780 non-null    int64
 10  alive                    780 non-null    object
 11  alone                    780 non-null    int64
 12  embarked_Q               780 non-null    bool
 13  embarked_S               780 non-null    bool
 14  embark_town_Queenstown   780 non-null    bool
 15  embark_town_Southampton  780 non-null    bool
dtypes: bool(4), float64(2), int64(7), object(3)
memory usage: 82.3+ KB

In [ ]:
df=pd.get_dummies(df,columns=["who"],drop_first=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    object
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    object
 10  alone                    780 non-null    int64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  embark_town_Queenstown   780 non-null    bool
 14  embark_town_Southampton  780 non-null    bool
 15  who_man                  780 non-null    bool
 16  who_woman                780 non-null    bool
dtypes: bool(6), float64(2), int64(7), object(2)
memory usage: 77.7+ KB

In [ ]:
df['alive']

0       no
1      yes
2      yes
3      yes
4       no
      ...
885     no
887    yes
888     no
889    yes
890     no
Name: alive, Length: 780, dtype: object

In [ ]:
df["alone"]=df["alone"].map({'yes':1,'no':0})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    object
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    object
 10  alone                    0 non-null      float64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  embark_town_Queenstown   780 non-null    bool
 14  embark_town_Southampton  780 non-null    bool
 15  who_man                  780 non-null    bool
 16  who_woman                780 non-null    bool
dtypes: bool(6), float64(3), int64(6), object(2)
memory usage: 77.7+ KB

In [ ]:
df['alive']

0       no
1      yes
2      yes
3      yes
4       no
      ...
885     no
887    yes
888     no
889    yes
890     no
Name: alive, Length: 780, dtype: object

In [ ]:
df["alive"]=df["alive"].map({'yes':1,'no':0})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    object
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  alone                    0 non-null      float64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  embark_town_Queenstown   780 non-null    bool
 14  embark_town_Southampton  780 non-null    bool
 15  who_man                  780 non-null    bool
 16  who_woman                780 non-null    bool
dtypes: bool(6), float64(3), int64(7), object(1)
memory usage: 77.7+ KB

In [ ]:
df['class'].value_counts()

class
Third     404
First     212
Second    164
Name: count, dtype: int64

In [ ]:
df['class']=df['class'].map({'First':3,'Second':2,'Third':1})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    int64
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  alone                    0 non-null      float64
 11  embarked_Q               780 non-null    bool
 12  embarked_S               780 non-null    bool
 13  embark_town_Queenstown   780 non-null    bool
 14  embark_town_Southampton  780 non-null    bool
 15  who_man                  780 non-null    bool
 16  who_woman                780 non-null    bool
dtypes: bool(6), float64(3), int64(8)
memory usage: 77.7 KB

In [ ]:
df["alone"].isnull().sum()

np.int64(780)

In [ ]:
df.drop(columns=["alone"], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    int64
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  embarked_Q               780 non-null    bool
 11  embarked_S               780 non-null    bool
 12  embark_town_Queenstown   780 non-null    bool
 13  embark_town_Southampton  780 non-null    bool
 14  who_man                  780 non-null    bool
 15  who_woman                780 non-null    bool
dtypes: bool(6), float64(2), int64(8)
memory usage: 71.6 KB

In [ ]:
df=df.replace({True:1,False:0})

/tmp/ipykernel_3049/3566451038.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({True:1,False:0})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 780 entries, 0 to 890
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 780 non-null    int64
 1   pclass                   780 non-null    int64
 2   sex                      780 non-null    int64
 3   age                      780 non-null    float64
 4   sibsp                    780 non-null    int64
 5   parch                    780 non-null    int64
 6   fare                     780 non-null    float64
 7   class                    780 non-null    int64
 8   adult_male               780 non-null    int64
 9   alive                    780 non-null    int64
 10  embarked_Q               780 non-null    int64
 11  embarked_S               780 non-null    int64
 12  embark_town_Queenstown   780 non-null    int64
 13  embark_town_Southampton  780 non-null    int64
 14  who_man                  780 non-null    int64
 15  who_woman                780 non-null    int64
dtypes: float64(2), int64(14)
memory usage: 103.6 KB

In [ ]:
df.to_csv("cleaned_titanic_yes.csv",index=False)

In [ ]:
files.download("cleaned_titanic_yes.csv")